clokep/django-querysetsequence

CHANGELOG.rst, queryset_sequence.py, tests/test_querysetsequence.py
Fixes #4 
This makes two major changes:
* Do not regenerate the comparator `key` function each iteration of the loop since it doesn't change.
* Use `attrgetter` to get sub-fields.
* (Also adds a test for a bug I almost caused while making these changes. :+1: )
=> Performance improvements

CHANGELOG.rst, README.rst, queryset_sequence.py, tests/test_querysetsequence.py
This adds `'#'` as a field lookup that supports a few things:
* Can be used in `order_by()` to first order by `QuerySet`, then follow the other field orderings. (This is useful to get a more optimal code path when iterating over the values in a `QuerySetSequence`.)
* Can be used in `filter()` / `exclude()` / `get()` to limit the `QuerySets` in use (by their order). This can be combined with normal [field lookups](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#field-lookups), e.g. `#__gt` to do `QuerySets` greater than some number.
Includes tests and documentation.
=> Support ordering / filtering / querying by the order of the QuerySets in a QuerySetSequence.

CHANGELOG.rst, queryset_sequence/_inheritance.py, tests/test_inheritance.py
Not providing `INHERITED_ATTRS` or `NOT_IMPLEMENTED_ATTRS` treats them as empty.
=> Add additional tests for PartialInheritanceMeta.

queryset_sequence/__init__.py, requirements.txt, tests/test_querysetsequence.py, tox.ini
#10 had a few minor issues with it. This also adds the `QuerySet` number to each returned item as an attribute.
=> Minor fixes to QuerySet number (#10)

queryset_sequence/__init__.py, tests/test_querysetsequence.py
When doing things like `gt` or `exact` lookups on an `IntegerField`, Django [casts the supplied value to an `int`](https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/db/models/fields/__init__.py#L1832-L1836) before using it. We should be doing the same here.
=> Treat QuerySet lookups as numbers.

queryset_sequence/__init__.py, tests/test_querysetsequence.py
The previous implementation of adding the `#` property would cause a model to share it across all instances (essentially polluting global scope). This PR fixes this by creating a `Proxy` model and setting the attribute on that instead.
This allows a model to be used in multiple `QuerySetSequence` objects at once (or multiple in the same `QuerySetSequence`).
=> Fixes for a model being used multiple times

README.rst, queryset_sequence/pagination.py, tests/test_pagination.py, tox.ini
`QuerySetSequence` works well by feeding it into a Django REST Framework view, but it fails under large `QuerySets` due to sorting concerns. This adds an efficient paginator which first paginates by the `QuerySet` number used, and then by the normal `Cursor` pagination of Django REST Framework.
=> Add an efficient Django REST Framework paginator

queryset_sequence/__init__.py
Tiny change, the string was missing a word so the message was not clear.
=> Fix exception string to include a missing word

tox.ini
Django REST Framework 3.5 was released.
=> Run tests on Django REST Framework 3.5.

.travis.yml, run_coveralls.py, tox.ini
Builds are failing since django-querysetsequence is not compatible with Django 1.11 (or master). I plan to fix this, but for now just don't test against those.
=> Fix travis builds

CHANGELOG.rst, queryset_sequence/__init__.py, setup.py, tests/test_querysetsequence.py
This fixes #23 (and adds tests for it).
The fix is pretty much that if there's only a single `QuerySet` left, you need to slice both the start and end off at the same time, otherwise you trim improperly.
=> Fix an issue where slicing of an individual QuerySet was broken.

CHANGELOG.rst, queryset_sequence/_inheritance.py, tests/test_inheritance.py
If you try to call a method that is marked as "not implemented" that has parameters the current code explodes with a non-helpful error message. This fixes it so you get the "QuerySetSequence does not implement <whatever>()".
Fixes #27
=> Fix raising NotImplementedError for methods with arguments.

queryset_sequence/__init__.py, tests/test_querysetsequence.py
It makes 2 times fewer queries because of `count()` calls. This
`count()` calls are quite inefficient when we use Postgres. They are
only required when slice (`set_limits`) is used.
=> Add optimization for not sliced querysets

.travis.yml, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py, tox.ini
Tests are still failing, because Django master is not supported.
https://travis-ci.org/michael-k/django-querysetsequence/builds/267246035
=> Support Django 1.11 & 2.0

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, requirements.txt, setup.py, tests/test_querysetsequence.py, tox.ini
This drops support for [unsupported Django versions](https://www.djangoproject.com/download/#supported-versions) (1.8, 1.9, and 1.10) and the corresponding Django REST Framework versions (3.2 and 3.3).
Django 1.8 is actually supported for a couple more months (through April, 2018), but there's some clean-up that can happen by dropping it.
=> Drop support for Django < 1.11 and corresponding DRF versions.

README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
Add support for calling `first()` and `last()`. These take into account ordering and compare the `first()` (or `last()`) of each individual `QuerySet`.
=> Support first() and last()

README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
When switching to not inheriting from `QuerySet` (and removing the inheritance helpers), we no longer raise `NotImplementedError` for methods that aren't implemented. This is nicer than just raising `AttributeError` in those cases.
=> Re-implement NotImplementedError

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
These simply pass through to the internal `QuerySet` instances.
=> Add support for defer(), only(), and using()

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
Support calling `update()`, which applies to all `QuerySets`. Updates are done in a transaction.
=> Support calling update()

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/models.py, tests/test_querysetsequence.py
Adds support for calling `annotate()`, which simply passes through to the underlying `QuerySet` instances.
=> Add support for calling annotate()

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
Adds support for `extra()`, which just calls each `QuerySet`.
=> Support extra() as a method.

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py, tox.ini
Add support for `explain()`, which just concatenates the strings of each `QuerySet`.
=> Support explain() on Django >= 2.1

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
Downstream projects desire the ability to retrieve the individual
`QuerySet` objects which form the `QuerySetSequence`.  This commit adds
a new `get_querysets` method as part of a stable public API to return
the list of `QuerySet` objects that the sequence object is currently
wrapping.
Tests and documentation updates are present, noting some of the caveats
around this method. Notably, the component querysets will differ from
those used to construct the original `QuerySetSequence` object if
methods have been invoked which modify the sequence. Also that the
order in which the `QuerySet` objects are returned is not guaranteed
to be constant.
Fixes #21
=> Add get_queryset method to expose QuerySet objects

tox.ini
Realized that #51 missed using Django 2.2 without Django REST Framework.
=> Test Django 2.2 without DRF.

.travis.yml, CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, queryset_sequence/pagination.py, tests/test_querysetsequence.py, tox.ini
This drops support for Python 2.7, adds support for Python 3.8.
This drops support for Django 2.0, Django 2.1 (both now unsupported), adds support for Django 3.0.
Fixes #58
=> Update supported versions for Django and DRF

CHANGELOG.rst, queryset_sequence/__init__.py
Fixes #60. I tested quickly in pypy3 and this didn't seem to actually cause a bug, but still good to fix it.
=> Fixes syntax warning about comparing to an integer using "is"

README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
Django 2.2 added a new `QuerySet` method. It isn't supported, but we should include it.
=> Add information about the bulk_update() method.

CHANGELOG.rst, README.rst, tox.ini
This adds Django REST Framework 3.11 to the build matrix and updates the CHANGELOG.
=> Add Django REST Framework 3.11 to the build matrix.

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py, tox.ini
This drops support for old Django and Django REST Framework versions.
=> Drop support for Django 1.11.

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py, tests/test_values.py
This adds support for calling `values()` on a `QuerySetSequence`. The index of the `QuerySet` can be included in the response by specifying `'#'` as one of the fields to return.
=> Add support for values()

CHANGELOG.rst, tox.ini
Doesn't seem to have any breaking changes: https://www.django-rest-framework.org/community/3.12-announcement/
=> Bump supported Django REST Framework to 3.12.

queryset_sequence/__init__.py, tests/test_querysetsequence.py
Hi Patrick,
Some user contributed query building code [similar to what django.contrib.admin does for search_fields](https://github.com/yourlabs/django-autocomplete-light/pull/1169).
This broke QSS support for two reasons:
- it combines `Q` objects with `|` and then calls qss.filter(built_filter)
- because of that, there is also code to detect if one of the filter is on an M2M table in which case it knowns it needs to call distinct
What do you think of this proposal ? We have a patch [ready in DAL](https://github.com/yourlabs/django-autocomplete-light/pull/1199) and I can still do any changes to fit the design decisions that you may want to make.
Thank you for your feedback
=> Support filter(*args)

queryset_sequence/__init__.py, tests/test_querysetsequence.py
This implementation of distinct() is simple and natural: call distinct() on all QuerySets of a QuerySetSequence.
=> Implement distinct()

tests/settings.py, tox.ini
See https://docs.djangoproject.com/en/dev/releases/3.2/#customizing-type-of-auto-created-primary-keys
=> Avoid a warning on Django >= 3.2.

CHANGELOG.rst, setup.py
This was already dropped in CI, but now require Python 3.6+.
=> Drop support for Python 3.5

CHANGELOG.rst, docs/api.rst, queryset_sequence/__init__.py, tests/test_querysetsequence.py
Django 4.0 added support for the [`contains()` method](https://docs.djangoproject.com/en/dev/ref/models/querysets/#contains) a more optimized version of using `in`.
=> Add support for `contains()`.

CHANGELOG.rst, README.rst, queryset_sequence/__init__.py, setup.cfg, tests/test_querysetsequence.py, tox.ini
Django 2.2 and 3.1 are no longer supported. Drops versions of django-rest-framework that didn't support at least Django 3.2.
Adds (basic) support for Django 4.1.
=> Drop support for old versions of Django / DRF, support Django 4.1.

.github/workflows/main.yml, CHANGELOG.rst, tox.ini
Also drops support for Django 3.2, 4.0, 4.1; django-rest-framework 3.11, 3.12, 3.13.
=> Support Django 5.0, and 5.1; Python 3.12.
